controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_homepage:
    path: /
    controller: App\Controller\HomeController::index

app_juegos:
    path: /juegos
    controller: App\Controller\HomeController::juegos

manuales:
    path: /manuales
    controller: App\Controller\HomeController::manuales

admin:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index

app_prueba:
    path: /prueba
    controller: App\Controller\PruebaController::index

user_register:
    path: /register
    controller: App\Controller\UserController::register
    methods: ['GET', 'POST']

app_user_inicio:
    path: /user/inicio
    controller: App\Controller\UserInicioController::inicio

