controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_homepage:
    path: /
    controller: App\Controller\HomeController::index

app_juegos:
    path: /juegos
    controller: App\Controller\HomeController::juegos

manuales:
    path: /manuales
    controller: App\Controller\HomeController::manuales

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

admin:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index


