controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_homepage:
    path: /
    controller: App\Controller\HomeController::index

dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index

app_juegos:
    path: /juegos
    controller: App\Controller\HomeController::juegos

manuales:
    path: /manuales
    controller: App\Controller\HomeController::manuales